/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.browse;

public final class R {
    public static final class array {
        public static final int dealSources=0x7f040001;
        public static final int options=0x7f040002;
        public static final int stores=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int deal=0x7f020000;
        public static final int dealicon=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int mappin_blue=0x7f020003;
    }
    public static final class id {
        public static final int editText1=0x7f060000;
        public static final int find=0x7f060002;
        public static final int spinner1=0x7f060001;
    }
    public static final class layout {
        public static final int deallistactivity=0x7f030000;
        public static final int locationselecter=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int display_type=0x7f050002;
        public static final int menu_edge_zooming=0x7f050008;
        public static final int menu_my_location=0x7f050006;
        public static final int menu_satellite_view=0x7f050005;
        public static final int menu_street_view=0x7f050004;
        public static final int menu_traffic_view=0x7f050007;
        public static final int your_location=0x7f050003;
        public static final int zip_code=0x7f050001;
    }
}
