/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.emer;

public final class R {
    public static final class array {
        public static final int bands=0x7f040002;
        public static final int colors=0x7f040000;
        public static final int planets=0x7f040001;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int solid_blue=0x7f050001;
        public static final int solid_green=0x7f050002;
        public static final int solid_red=0x7f050000;
        public static final int solid_yellow=0x7f050003;
    }
    public static final class drawable {
        public static final int blue=0x7f020006;
        public static final int emergency=0x7f020000;
        public static final int green=0x7f020007;
        public static final int icon=0x7f020001;
        public static final int icon1=0x7f020002;
        public static final int icon2=0x7f020003;
        public static final int icon3=0x7f020004;
        public static final int red=0x7f020005;
        public static final int screen_background_black=0x7f020009;
        public static final int translucent_background=0x7f02000a;
        public static final int transparent_background=0x7f02000b;
        public static final int yellow=0x7f020008;
    }
    public static final class id {
        public static final int editText1=0x7f070000;
        public static final int spinner1=0x7f070001;
    }
    public static final class layout {
        public static final int iceeditor=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int ice_edit_contact_label=0x7f06000a;
        public static final int ice_edit_name_label=0x7f060009;
        public static final int main_menu_call=0x7f060007;
        public static final int main_menu_delete=0x7f060004;
        public static final int main_menu_edit=0x7f060003;
        public static final int main_menu_exit=0x7f060008;
        public static final int main_menu_new=0x7f060005;
        public static final int main_menu_save=0x7f060006;
        public static final int main_menu_view=0x7f060002;
        public static final int main_title=0x7f060001;
    }
}
